sonar.organization=jsantos2808
sonar.projectKey=Jsantos2808_COCA-COLA
sonar.projectName=Coca-Cola Stock Portal

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**,data/**
sonar.coverage.exclusions=**/*.test.js,src/public/**
sonar.cpd.exclusions=src/public/**

sonar.sourceEncoding=UTF-8
